spring:
  application:
    name: raven-route

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  redis:
    host: ${site.redis}
    port: 6379
    pool:
      max-active: 20
      max-wait: 60000
      max-idle: 5
      min-idle: 1
  main:
    banner-mode: log
  cloud:
    zookeeper:
      connect-string: ${site.zookeeper}
      discovery:
        prefer-ip-address: true
  kafka:
    producer:
      acks: 1
      retries: 2
      buffer-memory: 33554432
      bootstrap-servers: ${site.kafka}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      max-in-flight-requests.per.connection: 1

server:
  port: 8030

# actuator相关配置
management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*' #开放所有监控接口

site:
  zookeeper: 127.0.0.1:2181
  redis: 127.0.0.1
  kafka: 127.0.0.1:9092

dubbo:
  registry:
    address: ${site.zookeeper}  #注册zookeeper的地址
  protocol:
    port: 30001
