spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/imdb?useUnicode=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  main:
    banner-mode: log

server:
  port: 7080
  servlet:
    contextPath: /admin
# Mybatis
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

#通用mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.tim.common.config.BaseMapper
  not-empty: true
  before: true
  identity: mysql

