spring:
  application:
    name: raven-access
  redis:
    host: ${address.redis}
    port: 6379
    pool:
      max-active: 20
      max-wait: 60000
      max-idle: 5
      min-idle: 1
  kafka:
    producer:
      acks: 1
      retries: 2
      buffer-memory: 33554432
      bootstrap-servers: ${address.kafka}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      max-in-flight-requests.per.connection: 1

  main:
    banner-mode: log
  cloud:
    zookeeper:
      connect-string: ${address.zookeeper}:2181
      discovery:
        prefer-ip-address: true
        metadata:
          tcp-port: ${netty.tcp.port}
          websocket-port: ${netty.websocket.port}
          internal-port: ${netty.internal.port}
server:
  port: 8010

# actuator相关配置
management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*' #开放所有监控接口

netty:
  tcp:
    port: 7010
  websocket:
    port: 7011
  internal:
    port: 7012

node:
  data-center-id: 1
  machine-id: 1

address:
  zookeeper: 127.0.0.1
  redis: 127.0.0.1
  kafka: 127.0.0.1:9092
