spring:
  application:
    name: tim-zuul
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

zuul:
  ignored-services: '*'
  routes:
    api:
      path: /api/**
      serviceId: TIM-ROUTE
    admin-api:
      path: /admin-api/**
      serviceId: TIM-ADMIN
  ribbon:
    eager-load:
      enabled: true # 立即加载ribbon负载均衡器
  servlet-path: /tim-zuul

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 5000

# 熔断时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


# actuator相关配置
management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*' #开放所有监控接口
