spring:
  application:
    name: tim-access
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 20
      max-wait: 60000
      max-idle: 5
      min-idle: 1
  main:
    banner-mode: log
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        prefer-ip-address: true
        metadata:
          netty-port: ${netty.server.port}
server:
  port: 8010

netty:
  server:
    port: 7010

node:
  data-center-id: 1
  machine-id: 1



