spring:
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 20
      max-wait: 60000
      max-idle: 5
      min-idle: 1
  main:
      banner-mode: log
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtual-host: /
netty:
  server:
    port: 7070
